services:
  app:
    image: job_post
    container_name: job_post
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - app_data:/root/
    env_file:
      - .env
    restart: always
    networks:
      - network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  app_data:
  mongo_data: